services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pcshop_db
    # hostname: pcshop_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - pcshop-network
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: always
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    networks:
      - pcshop-network

volumes:
  sqlserver_data:
  cloudbeaver_data:

networks:
  pcshop-network:
    driver: bridge